---
proxies:
        
  - name: trojan
    server: google.com
    port: 443
    type: trojan
    password: trojan
    skip-cert-verify: true
    sni: google.com
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: google.com
    udp: true